
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/xcode-project"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-steplib/steps-xcode-archive"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[prune]
  go-tests = true
  unused-packages = true
